### ISSUE TITLE
edit shape not possible

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ecpo-annotator#101]
editing shapes is no more possible. no matter, if existing or new shape. 
symptoms: after switch into edit-mode, the edge circles do appear, but moving them around does NOT affect the shape itself. dragging them around and saving the new coordinates of the edges is lost after a save.

**Comment by line-o** [comment]
Please recheck with the latest version whenever the IIIF serves the facsimiles again.

**Comment by line-o** [comment]
Please recheck again the recent version had duplicate lines in the key component. Fixed with 0347300c6edd7ab4755aa2b5723644fc8d7658d6
