### ISSUE TITLE
polygon: eckpunkte transparent

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#36]
In GitLab by @MatthiasArnold on Jan 23, 2019, 16:19

zeichnet man ein polygon, werden die eckpunkte durch große kreise markiert (wie im edit-mode bei rechecken, was durchaus ein feature ist). diese punkt-markierungen sollten aber transparent sein, dass wenn bei kleineren strukturen nahe beieinanderliegende punkte gesetzt werden müssen, der hintergund noch sichtbar bleibt.

**Comment by line-o** [comment]
Fixed see screenshot
![Screenshot 2019-12-18 at 16 42 37](https://user-images.githubusercontent.com/657222/71100504-71302800-21b5-11ea-8240-55bc46408a1c.png)
