### ISSUE TITLE
when switching from edit to navigation mode point handles are not removed [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#43]
The original issue

	Id: 42
	Title: when switching from edit to navigation mode point handles are not removed

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by line-o** [comment]
will be fixed with #74
