### ISSUE TITLE
cancelling polygon creation creates unfinished shape with broken annotation [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#44]
The original issue

	Id: 43
	Title: cancelling polygon creation creates unfinished shape with broken annotation

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by line-o** [comment]
could not reproduce
