### ISSUE TITLE
polygon shapes are not transparent [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#45]
The original issue

	Id: 44
	Title: polygon shapes are not transparent

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by line-o** [comment]
I think this issue is fixed.
