### ISSUE TITLE
remap keyboard commands for usability [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#47]
The original issue

	Id: 46
	Title: remap keyboard commands for usability

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by line-o** [comment]
the key mapping can be changed here
https://github.com/exc-asia-and-europe/ecpo-annotator/blob/4abbfd27284e6e6be5c2e1cd77fad798cb30a84d/components/existdb-image-annotator.html#L890

**Comment by line-o** [comment]
Closing as implemented. See comment above.
