### ISSUE TITLE
determine format for groups [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#51]
The original issue

	Id: 50
	Title: determine format for groups

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by line-o** [comment]
The group annotation format is defined as follows:

- **body** must contain 
  - an entry with **type** `GroupAnnotation` and a **color** property with a valid CSS-color 
  - an valid entry of **type** `CategoryLabel`
- **target** with
  - one or more valid **annotation**(s)
  - annotations CAN target multiple documents (untested in current implementation)
