### ISSUE TITLE
group re-assign not stored [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#56]
The original issue

	Id: 55
	Title: group re-assign not stored

could not be created.
- create annotation
- assign to group
- store
- re-assign to new group
- store
- reload

expected

- annotation is assigned to new group

actual 

- annotation is still in old group

**Comment by duncdrum** [comment]
originally assigned to @line-o

**Comment by line-o** [comment]
will be fixed with #74
