### ISSUE TITLE
select annotation assigned to a group [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#57]
The original issue

	Id: 56
	Title: select annotation assigned to a group

could not be created.

- create annotation
- assign to group
- switch to select mode
- switch to shape mode
- select shape

expected

- shape is selected

actual

- group is selected

**Comment by duncdrum** [comment]
originally assigned to @line-o

**Comment by line-o** [comment]
this will be fixed with #74
