### ISSUE TITLE
doku [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#64]
The original issue

	Id: 63
	Title: doku

could not be created.
vor allem API-Dokumentation des Web-Annotation-Protocol Services

**Comment by duncdrum** [comment]
originally assigned to @line-o

**Comment by line-o** [comment]
Falls noch nicht erfüllt, bitte ein ticket auf https://github.com/eXistSolutions/web-annotation-service
aufmachen.
