### ISSUE TITLE
some annotations cannot be deleted (keep reappearing)

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#68]
In GitLab by @MatthiasArnold on Jul 29, 2019, 22:18

some annotations keep reappearing, even though they have been deleted (and saved) multiple times already. example: 

![image](/uploads/37ee2f3812011b4ca5ea43d7040fe54d/image.png)

**Comment by line-o** [comment]
@duncdrum the file above does not exist

found:
1. jb_3796_1939-04-22_0001+0004.tif
2. jb_3804_1939-04-30_0001+0004.tif

likely the latter is meant here

**Comment by line-o** [comment]
Affected are all annotations with
- a selector of type `SVGSelector` and
- a missing id attribute in the `svg:g` element

These annotations also do not show the ID and type in the right sidebar when selected.

**Comment by MatthiasArnold** [comment]
> @MatthiasArnold the file above does not exist
> found:
>     1. jb_3796_1939-04-22_0001+0004.tif
>     2. jb_3804_1939-04-30_0001+0004.tif
> likely the latter is meant here

i've started a documentation of the problems here:
https://docs.google.com/spreadsheets/d/1dXUayhct5VxZyb38qYKsaJ6RP5CDv8VkDIfX6T5zxP4/edit#gid=0
and just shared it with you

**Comment by line-o** [comment]
bug was fixed with https://github.com/exc-asia-and-europe/ecpo-annotator/pull/73
