### ISSUE TITLE
cannot add new shape

### ISSUE THREAD

**Issue by MatthiasArnold** [exc-asia-and-europe/ecpo-annotator#96]
while it was possible to remove superfluous shapes from fold jb_3795_1939-04-21_0005to0008 and adjuste the edges of existing shapes, and add some new shapes cf. #68 , adding yet another shape is not possible.
the fold has 89 shapes. if i add a new shape and hit "save", the save message appears ("90 shapes saved") but after reloading the fold that last shape does not appear and it says "89 shapes saved".

<img width="549" alt="2021-07-31 14_49_43-Image Annotator demo with list and 1 more page - Profile 1 - Microsoft​ Edge" src="https://user-images.githubusercontent.com/3436613/127740419-ed9635c6-d088-4d9e-bd4f-1ccb76d49c08.png">

<img width="547" alt="2021-07-31 14_50_13-Image Annotator demo with list and 1 more page - Profile 1 - Microsoft​ Edge" src="https://user-images.githubusercontent.com/3436613/127740423-315a7743-4540-40e8-887a-faa6a99f75de.png">

**Comment by line-o** [comment]
Please retest with v2.2.1
